--
-- This is a VHDL package file generated by vhdlpkg.xsl
--
-- Implements a 8 bit address wide register map as VHDL package
--
-- (c) 2007-2011, Martin Strubel // hackfin@section5.ch
--
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;

use work.iomap_config.all;

package ghdlsim is

-- Address segment 'FPGA_Registermap'
--         Offset: 
constant R_MagicId           : regaddr_t := x"00";
-- Control register
constant R_Control           : regaddr_t := x"02";
    -- Enable FPGA engine
    constant              B_ENABLE : natural := 0;    -- If set, slow down simulation
    constant              B_THROTTLE : natural := 1;    -- RESET FPGA engine
    constant              B_RESET : natural := 7;
end ghdlsim;

